### ISSUE TITLE
health scanner reprocessing 3

### ISSUE THREAD

**Issue by mindrones** [nestauk/nesta#126]
- NIH:
   - [x] add  MeSH labels (#101)
   - [ ] add `url_nih_org` or `url_pubmed_org` (*)
   - [ ] bad data quality in some NiH (#51)
   - [ ] de-duplicate items collecting funding rounds (#135)
- Meetup:
   - [ ] add MeSH labels (#127)
   - [ ] rename meetup’s [`url_of_group`](https://github.com/nestauk/nesta/blob/dev/nesta/production/orms/meetup_es_config.json#L124) to `url_meetup_group` (*)
   - [ ] Identify member origins, according to some statistical method
   - [ ] Also add member origins as ES `object` with relative fractions of origin mapped to each country.
   - [ ] Pipe member origins to ES
   - [ ] Re-collect meetup data (this is a huge task, probably requires rewriting, will be a separate issue. note: one idea is to simply collect all meetup data to simplify the collection procedure)
- CB
   - [ ] analyze `terms_roles_organisation` as array of `keyword`s #150
   - [ ] eventually convert [`datetime_updated_organisation`](https://github.com/nestauk/nesta/blob/dev/nesta/production/orms/crunchbase_es_config.json#L45) to `"yyyy-MM-dd"` and rename to `date_updated_organisation`
- [ ] Whilst re-collecting the meetup data, take care to ensure encodings are dealt with cleanly. See `urlname='Lets-do-yoga-in-English-and-Japanese'` in `tier_0` (#129)
- [ ] (*) add the new alias `url_source` (#128)
- [ ] [`sdg_labels`](https://github.com/nestauk/nesta/blob/master/nesta/production/schemas/tier_1/aliases/health_scanner.json#L63) (#95) as sorted arrays
- [ ] `cost_ref` [is still pointing to non deflated values](https://github.com/nestauk/nesta/blob/master/nesta/production/schemas/tier_1/aliases/health_scanner.json#L18) (#93)
- [ ] `novelty` [is still pointing to cost values](https://github.com/nestauk/nesta/blob/master/nesta/production/schemas/tier_1/aliases/health_scanner.json#L56) (#94)

Related to: #81, #96, #102

**Comment by mindrones** [comment]
Closed by #112
