### ISSUE TITLE
health scanner reprocessing 5

### ISSUE THREAD

**Issue by mindrones** [nestauk/nesta#168]
- NIH:
   - [ ] 👀 bad data quality in some NiH (#51)
   - [ ] rename the type from `paper` to `project`
- Meetup:
   - [ ] Identify member origins, according to some statistical method
   - [ ] Also add member origins as ES `object` with relative fractions of origin mapped to each country.
   - [ ] Pipe member origins to ES
   - [ ] Re-collect meetup data (this is a huge task, probably requires rewriting, will be a separate issue. note: one idea is to simply collect all meetup data to simplify the collection procedure)
- CB
   - [ ] 💅  analyze `terms_roles_organisation` as array of `keyword`s #150
   - [ ] eventually convert [`datetime_updated_organisation`](https://github.com/nestauk/nesta/blob/dev/nesta/production/orms/crunchbase_es_config.json#L45) to `"yyyy-MM-dd"` and rename to `date_updated_organisation`
- ALL
   - [ ] ⚠️ [`sdg_labels`](https://github.com/nestauk/nesta/blob/master/nesta/production/schemas/tier_1/aliases/health_scanner.json#L63) (#95) as sorted arrays
   - [ ] ⚠️ [`novelty`](https://github.com/nestauk/nesta/blob/master/nesta/production/schemas/tier_1/aliases/health_scanner.json#L56) (#94)
   - [ ] 👀 take care to ensure encodings are dealt with cleanly. See `urlname='Lets-do-yoga-in-English-and-Japanese'` in `tier_0` (#129) 

Related to: #81, #96, #102, #126, #161
