### ISSUE TITLE
First reprocessing of health scanner data

### ISSUE THREAD

**Issue by jaklinger** [nestauk/nesta#81]
update: running first dev pipeline tests with following changes (will appear formally in a changelog):
• ElasticsearchPlus developed to chain together row-wise transformations such as:
• “company” (for crunchbase) or “paper” (for nih) added as new field `type_of_entity`
• applying `null` values to fields as described in https://github.com/nestauk/nesta/blob/health2/nesta/production/schemas/tier_1/field_null_mappings/health_scanner.json
• Changed “crunchbase” to “companies” as `_index` name, in accordance with Ts&Cs of new crunchbase contract
• Aliases applied as described in https://github.com/nestauk/nesta/blob/health2/nesta/production/schemas/tier_1/aliases/health_scanner.json
• empty string filtered to `null`
• countries automatically detected in large text
• `terms_` fields are automatically listified, with the most likely delimiter automatically identified. In practice, this means the `;` seperated values will now be a proper json array from the ES response.
• Geographic lat lon values are now always floats

other changes:
• State names in CB data

Things not done yet (relatively short tasks) which will go into the same release:
⇒ Mixed analyzers for country and city lists
⇒ Add funders to CB and NiH
⇒ Add continent names

I’ll get in touch once the pipeline is flowing properly

**Comment by jaklinger** [comment]
@mindrones @russwinch @pngwn 
if you could take a look at the new index `companies` to confirm the above changes for CB. Note that it also contains new data (i.e. updates and new entries). New NiH data to follow in the nearish future.

**Comment by mindrones** [comment]
Here are my previous observations (Slack, May 16th 4:29PM).

• “company” (for crunchbase) or “paper” (for nih) added as new field `type_of_entity`

OK

> • applying `null` values to fields as described in https://github.com/nestauk/nesta/blob/health2/nesta/production/schemas/tier_1/field_null_mappings/health_scanner.json

What about `cost` for items not having a currency?
Should we consider the cost null or?
Maybe a missing currency might mean implicit currency (like, a USA-oriented DB might imply USD but can we use that?)

> • Changed “crunchbase” to “companies” as `_index` name, in accordance with Ts&Cs of new crunchbase contract

OK

> • Aliases applied as described in https://github.com/nestauk/nesta/blob/health2/nesta/production/schemas/tier_1/aliases/health_scanner.json

Wondering why:

```
"novelty": {
  "nih": "cost_total_project",
  "crunchbase": "cost_of_funding"
},
```

rather than

```
"novelty": {
  "nih": "_novelty_rank",
  "crunchbase": "_novelty_rank"
},
```

(or similar naming)

> • empty string filtered to `null`

OK

> • countries automatically detected in large text

OK

> • `terms_` fields are automatically listified, with the most likely delimiter automatically identified. In practice, this means the `;` seperated values will now be a proper json array from the ES response.

OK

> • Geographic lat lon values are now always floats

OK

> other changes:
> • State names in CB data

Now that we decided to send ID for countries, maybe it’s trivial to add a `id_state_organisation` to NIH too?
Apologies for this, I’ve been on the verge of talking about it 3 or 4 times and I didn’t have a chance and then I forgot.

> Things not done yet (relatively short tasks) which will go into the same release:
> ⇒ Mixed analyzers for country and city lists

re: analyzers

Many more fields should have mixed analyzers, as I was doing in this https://github.com/nestauk/nesta/pull/74/files, see https://github.com/nestauk/nesta/blob/2d1cc12fc73959afa1c2bd43e36c34119fb1ba64/nesta/production/orms/crunchbase_es_config.json

Basically:
- all of geographic entities (continent, country, state, region, city)
- categories (terms_category_organisation, terms_subcategory_organisation)
- labels (_terms_mesh_description)

Also from the PR, have a look at the types I was suggesting: for example `url_of_organisation` should be of type `text` rather than `keyword`: this lets us find items with “cancer” or similar terms in the URL.

In what branch is this?

So that I can have a quick look at `nesta/production/orms/*_es_config.json` files to confirm the types.

> ⇒ Add funders to CB and NiH

OK.

Do we have some quick coverage of this?

> ⇒ Add continent names

OK. Do we want to also use IDs for continents? At this point we might just use a lookup table for everything geographic to slim down the response as much as possible (1000 items would have 100s of repetitions of 6 continent strings).

**Comment by mindrones** [comment]
Another thing still to discuss is where to find an endpoint to fetch the mappings among ids and labels for geographic entities (countries, states), and potentially other things like regions, continents, categories and ordinal values in general, to avoid repetitions in the query response.

**Comment by jaklinger** [comment]
@mindrones @pngwn @russwinch  further to the last message: reprocessed NiH data is appearing at `nih_v3`. Please take a look at this when you have time.

**Comment by jaklinger** [comment]
`nih_v3` finished processing overnight. Note an additional cleaning which I didn't mention was converting any *UPPER CASE* text longer than 3 chars (to avoid the ISOs) to *Camel Case*. Naturally it leads to some acronyms being Camel Case'd, but I think the in overwhelming majority of cases it cleans the result. 

There are some quirks in the `countryTags` field (such as "US" and "India" being inferred from the term "American Indian") but again in the overwhelming majority the result is pretty good.

**Comment by jaklinger** [comment]
Rerunning `nih` data collection since it appears many projects and abstracts are missing.

**Comment by russwinch** [comment]
Also mesh terms are missing from the reprocessed crunchbase data due to a missing task. I'm looking into this now.

**Comment by jaklinger** [comment]
Mesh terms also missing from NiH data as these need to be reprocessed (recall this stage is manual, which George does). 

Nevertheless, please review the data quality, as adding in the mesh terms can happen in parallel.

**Comment by jaklinger** [comment]
Just to follow up on the crunchbase mesh terms, these are being added now. Expect some down time whilst these add (around an hour from now).

**Comment by jaklinger** [comment]
further follow up on crunchbase mesh terms, these are now done.

**Comment by mindrones** [comment]
(marking with `(*)` things that could be separate issues)

- mapping:
  - [ ] mixed analysers, use `keyword` and `text` for
      - all of geographic entities (continent, country, state, region, city)
      - `terms_category_organisation`, `terms_subcategory_organisation`, `terms_mesh_description`
  - [ ] possibly sort alphabetically these config files (ignoring the initial "_"  like I did in #74:
    - https://github.com/nestauk/nesta/blob/master/nesta/production/orms/crunchbase_es_config.json
    - https://github.com/nestauk/nesta/blob/master/nesta/production/orms/nih_es_config.json
  - [ ] rename [`countries_codes`](https://github.com/nestauk/nesta/blob/master/nesta/production/schemas/tier_1/aliases/health_scanner.json#L22) to `countries_ids` for consistency
- [ ] (*) check that we're using correct values in [`sdg_labels`](https://github.com/nestauk/nesta/blob/master/nesta/production/schemas/tier_1/aliases/health_scanner.json#L63)
- [ ] (*) `cost_ref` [is still pointing to non de-inflated values](https://github.com/nestauk/nesta/blob/master/nesta/production/schemas/tier_1/aliases/health_scanner.json#L18)
- [ ] (*) `novelty` [is still pointing to cost values](https://github.com/nestauk/nesta/blob/master/nesta/production/schemas/tier_1/aliases/health_scanner.json#L56)
- geographic information:
  - [ ] (*) add continent ids
  - [ ] (*) add `id_state_organisation` on NIH #73 
  - [ ] (*) Some companies in the United States don't have `id_state_organisation` [1]
  - [ ] (*) host a static lookup table (see nestauk/health-innovation-scanner/issues/25), to be kept in sync with geo codes used in nestauk/nesta, for:
      - continents
      - countries
      - states
- [ ] (*) nullify cost fields for items not having a currency
- [ ] (*) Add funders to CB and NiH

[1]
```js
{
  "_index": "crunchbase_orgs_v1",
  "_type": "_doc",
  "_id": "7ce5bb09-f734-255b-4f9a-9c6e31cabf58",
  "_score": 26.6893,
  "_source": {
    "placeName_country_organisation": "United States",
    "textBody_summary_organisation": "Puma Biotechnology acquires and develops innovative products for the treatment of various forms of cancer.",
    "currency_of_funding": "USD",
    "terms_mesh_description": [
      "Animals",
      "Humans",
      "N-(4-(3-chloro-4-(2-pyridinylmethoxy)anilino)-3-cyano-7-ethoxy-6-quinolyl)-4-(dimethylamino)-2-butenamide",
      "Puma",
      "Quinolines",
      "Breast Neoplasms",
      "Protein Kinase Inhibitors",
      "Biotechnology",
      "Biological Products",
      "Protein-Tyrosine Kinases"
    ],
    "coordinate_of_city": {
      "lon": -118.242767,
      "lat": 34.053683
    },
    "date_birth_organisation": "2010-01-01",
    "textBody_descriptive_organisation": "Puma Biotechnology, Inc., is a development stage biopharmaceutical company that acquires and develops innovative products for the treatment of various forms of cancer. The Company focuses on in-licensing drug candidates that are undergoing or have already completed initial clinical testing for the treatment of cancer and then seeks to further develop those drug candidates for commercial use. The Company is initially focused on the development of PB-272 (oral neratinib), a potent irreversible tyrosine kinase inhibitor, for the treatment of patients with HER2 positive metastatic breast cancer.",
    "cost_of_funding": 674300000,
    "name_of_organisation": "Puma Biotechnology",
    "id_iso2_country": "US",
    "placeName_city_organisation": "Los Angeles"
  }
},
```

**Comment by jaklinger** [comment]
@luca, please refer to the index `companies` (not `crunchbase`). The above example [1] is fixed in https://search-health-scanner-5cs7g52446h7qscocqmiky5dn4.eu-west-2.es.amazonaws.com/companies/_doc/7ce5bb09-f734-255b-4f9a-9c6e31cabf58

**Comment by jaklinger** [comment]
@mindrones please use the `companies` index. The above issue regarding [1] is fixed (see https://search-health-scanner-5cs7g52446h7qscocqmiky5dn4.eu-west-2.es.amazonaws.com/companies/_doc/7ce5bb09-f734-255b-4f9a-9c6e31cabf58)

**Comment by jaklinger** [comment]
Note: re-rerunning production processing of NiH and CB now. These will appear under the `companies_v1` and `nih_v4` indexes.

**Comment by jaklinger** [comment]
Following up on previous message: `companies_v1` and `nih_v4` are finished processing. Just waiting on mesh labels for `nih`.

**Comment by mindrones** [comment]
Moved part of these tasks to #102
